// constants/authConstants.js
export const WORKER_LOGIN_REQUEST = 'WORKER_LOGIN_REQUEST';
export const WORKER_LOGIN_SUCCESS = 'WORKER_LOGIN_SUCCESS';
export const WORKER_LOGIN_FAILURE = 'WORKER_LOGIN_FAILURE';
export const WORKER_LOGOUT = 'WORKER_LOGOUT';

export const FINDER_LOGIN_REQUEST = 'FINDER_LOGIN_REQUEST';
export const FINDER_LOGIN_SUCCESS = 'FINDER_LOGIN_SUCCESS';
export const FINDER_LOGIN_FAILURE = 'FINDER_LOGIN_FAILURE';
export const FINDER_LOGOUT = 'FINDER_LOGOUT';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const VERIFY_RESET_CODE_REQUEST = 'VERIFY_RESET_CODE_REQUEST';
export const VERIFY_RESET_CODE_SUCCESS = 'VERIFY_RESET_CODE_SUCCESS';
export const VERIFY_RESET_CODE_FAILURE = 'VERIFY_RESET_CODE_FAILURE';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

export const CLEAR_WORKER_STATE = 'CLEAR_WORKER_STATE';
export const CLEAR_FINDER_STATE = 'CLEAR_FINDER_STATE';

export const UPDATE_WORKER_LOCAL_PROFILE = 'UPDATE_WORKER_LOCAL_PROFILE';
export const UPDATE_WORKER_PROFILE_REQUEST = 'UPDATE_WORKER_PROFILE_REQUEST';
export const UPDATE_WORKER_PROFILE_SUCCESS = 'UPDATE_WORKER_PROFILE_SUCCESS';
export const UPDATE_WORKER_PROFILE_FAILURE = 'UPDATE_WORKER_PROFILE_FAILURE';

