export const FEEDBACK_SUBMIT_REQUEST = 'FEEDBACK_SUBMIT_REQUEST';
export const FEEDBACK_SUBMIT_SUCCESS = 'FEEDBACK_SUBMIT_SUCCESS';
export const FEEDBACK_SUBMIT_FAIL = 'FEEDBACK_SUBMIT_FAIL';

export const FETCH_FEEDBACKS_REQUEST = 'FETCH_FEEDBACKS_REQUEST';
export const FETCH_FEEDBACKS_SUCCESS = 'FETCH_FEEDBACKS_SUCCESS';
export const FETCH_FEEDBACKS_FAIL = 'FETCH_FEEDBACKS_FAIL';